### ISSUE TITLE
Code inconsistent in function Clean_Func_Calls

### ISSUE THREAD

**Issue by pse1202** [R3MRUM/PSDecode#10]
https://github.com/R3MRUM/PSDecode/blob/2c6badf8e34323be404350ce9a595b8a7b875419/PSDecode.psm1#L271

https://github.com/R3MRUM/PSDecode/blob/2c6badf8e34323be404350ce9a595b8a7b875419/PSDecode.psm1#L272

In the function Clean_Func_Calls, the verbose logging suggests removing the parentheses and the actual command removes the quotes.

However, I think the code is supposed to remove the backticks from the function names judging by the name "Clean_Func_Calls".

Can this be checked? Thanks

BTW, thanks for this useful tool.

**Comment by R3MRUM** [comment]
Good catch! I just pushed an updated version with messaging that reflects the actual action being performed.

**Comment by R3MRUM** [comment]
accidentally introduced a new syntax error. fixing now

**Comment by R3MRUM** [comment]
Should be fixed now. If you can, please verify on your end so I can close this out

**Comment by pse1202** [comment]
LGTM
