### ISSUE TITLE
new-object NEt.WeBclIeNT vs [NEt.WeBclIeNT]::New() 

### ISSUE THREAD

**Issue by sefai** [R3MRUM/PSDecode#13]
Hi there,

It seems the new-object override only works for the function, but not to class instantiation with the New() constructor. Do you think it is possible also to override this?

Kind Regards,

**Comment by R3MRUM** [comment]
Hey Sefai,

I dont see why not but I would have to research it a bit more. Would you be willing to share the malicious script with me so that I can use it in my testing?

**Comment by sefai** [comment]
Actually It's not from a malware script, I was playing with the PSDecode module and I've changed this line:

$Rizdsqikt=new-object NEt.WeBclIeNT;

to this:

$Rizdsqikt=[NEt.WeBclIeNT]::New();

Kind Regards,

**Comment by sefai** [comment]
If it helps the original script is this. I am working on the decoder script saved in the temp directory.

[emotet.txt](https://github.com/R3MRUM/PSDecode/files/4016742/emotet.txt)

**Comment by sefai** [comment]
It seems I can't find a way to override functions/methods from .Net in Powershell. There is also a line that starts the downloaded executable in the script; [Diagnostics.Process]::Start which cannot be overriden using the same technique. Did you have any luck?

**Comment by R3MRUM** [comment]
Hey sefai,

Unfortunately there will be an infinite number of ways to defeat PSDecode. It is just the nature of the cat and mouse game that we play. The goal of PSDecode isn't to decode all the things but to focus on common encoding/obfuscation techniques currently employed by malware authors and adjust accordingly as the threat evolves.
