### ISSUE TITLE
Stuck at Layer 1

### ISSUE THREAD

**Issue by BrandonGDossantos** [R3MRUM/PSDecode#3]
I ran PSDecode against a different Emotet script and the decoder stopped at Layer 1. I then used your example and it too stopped at Layer 1 and exited. 
![image](https://user-images.githubusercontent.com/17682268/41160343-621a1de6-6afd-11e8-9be3-ee1889e9a4f0.png)

**Comment by R3MRUM** [comment]
As I did make some recent updates, i just tested the current version of PSDecode against the original example that is provided on the PSDecode main page and I confirmed it decoded all of the layers just fine.

When you copy/pasted the example from the main page, did you make sure to remove all newline characters? The encoded PowerShell should just be one long single line.

Are you able to share the new Emotet PowerShell that your were attempting to decode?
