### ISSUE TITLE
Unexpected token 'if' in expression or statement

### ISSUE THREAD

**Issue by orblatt** [R3MRUM/PSDecode#4]
Can you help me with this one?

powershell.exe : Unexpected token 'if' in expression or statement.
At C:\Windows\System32\WindowsPowerShell\v1.0\Modules\PSDecode\PSDecode.psm1:150 char:38
+         $encoded_script = (powershell <<<<  $decoder)
    + CategoryInfo          : NotSpecified: (Unexpected toke...n or statement.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
At line:70 char:308
.
.
.
+ CategoryInfo          : ParserError: (if:String) [], ParentContainsError 

   RecordException

    + FullyQualifiedErrorId : UnexpectedToken

**Comment by R3MRUM** [comment]
are you able to provide the original script that you were attempting to decode? this will help me reproduce the error and troubleshoot.
