### ISSUE TITLE
The filename or extension is too long error

### ISSUE THREAD

**Issue by Shirofune-Security** [R3MRUM/PSDecode#5]
Program 'powershell.exe' failed to run: The filename or extension is too long
At C:\tools\PSDecode-master\PSDecode.psm1:150 char:28
+         $encoded_script = (powershell $decoder)
+                            ~~~~~~~~~~~~~~~~~~~.
At C:\tools\PSDecode-master\PSDecode.psm1:150 char:9
+         $encoded_script = (powershell $decoder)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
 
Happens when trying to deobfuscate the following malware:
https://www.virustotal.com/#/file/d943bc6dc7614894cc1c741c6c18ac2dbd2c5069f3ab9bc9def5cc2661e54dee/detection

**Comment by R3MRUM** [comment]
Hey Shirofun-Security,

Sorry for not getting back to you sooner. I had not seen your issue post until recently. Given the complexity of the powershell provided, I am not sure if this is something that PSDecode will ever be able to handle. Your script reflectively injects and executes one of two executables based on system architecture. Let me take some time to think about options and see what I can do. I'll leave this issue open for now.

Thank you for reporting this.

**Comment by R3MRUM** [comment]
Technically this was fixed in v4.0 but v4.1 now includes the ability to also extract out the embedded executables that are base64 encoded.
