### ISSUE TITLE
(FIXED. READ IT!!!) PSDecode various syntax errors

### ISSUE THREAD

**Issue by LucaReggiannini** [R3MRUM/PSDecode#7]
Hello,
i'm editing this post because i found i FIX.

The error was:
**https://pastebin.com/vJPu85nH**
when trying to use: **import-module PSDecode**

On line 164:
IF I OPEN IT WITH NOTEPAD I GET
` if($b64_decoded_ascii -match '^(.\x00){8,}’){`
IF I OPEN IT WITH Powershell ISE I GET
`if($b64_decoded_ascii -match '^(.\x00){8,}â€™){`

The second line of code contains a non ending string
`if($b64_decoded_ascii -match '`
instead of
`if($b64_decoded_ascii -match ''`

so it comments a large portion of code below and makes it non working

So the line of code should actually be 
`if($b64_decoded_ascii -match '^(.\x00){8,}â€™'){`

this will make the program work again

EDIT: actually sometime, **randomly, the ISE will show the wrong line.**.. omg this problem is strange...

**Comment by R3MRUM** [comment]
Thank you for spotting this. I had something similar occur with v3.0 that I just pushed as well. Seems like there is a copy/paste issue that is resulting in invalid characters. I'll have to keep this in mind when pushing future revisions. Would you mind pulling the recent revision to ensure that my fix works on your system?
